### ISSUE TITLE
ERROR: [NormalModesCalculationError] when using --anm with --membrane

### ISSUE THREAD

**Issue by Srilok** [lightdock/lightdock#15]
I am trying to run the [membrane-associated protein docking](https://lightdock.org/tutorials/membrane) tutorial but also including ligand flexibility (specifying `--anm` flag). 

I get the following error during setup

`lightdock3_setup.py receptor_membrane_P.pdb 2hdi_unbound_B.pdb --noxt --noh --membrane --anm`

```
[lightdock3_setup] INFO: Ignoring OXT atoms
[lightdock3_setup] INFO: Ignoring Hydrogen atoms
[lightdock3_setup] INFO: Reading structure from receptor_membrane_P.pdb PDB file...
[pdb] WARNING: Possible problem: [SideChainError] Incomplete sidechain for residue ARG.111
[pdb] WARNING: Possible problem: [SideChainError] Incomplete sidechain for residue LYS.212
[pdb] WARNING: Possible problem: [SideChainError] Incomplete sidechain for residue ARG.643
[pdb] WARNING: Possible problem: [SideChainError] Incomplete sidechain for residue ASN.649
[lightdock3_setup] INFO: 5155 atoms, 1056 residues read.
[lightdock3_setup] INFO: Ignoring OXT atoms
[lightdock3_setup] INFO: Ignoring Hydrogen atoms
[lightdock3_setup] INFO: Reading structure from 2hdi_unbound_B.pdb PDB file...
[lightdock3_setup] INFO: 810 atoms, 103 residues read.
[lightdock3_setup] INFO: Calculating reference points for receptor receptor_membrane_P.pdb...
[lightdock3_setup] INFO: Reference points for receptor found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating reference points for ligand 2hdi_unbound_B.pdb...
[lightdock3_setup] INFO: Reference points for ligand found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating ANM for receptor molecule...
[ANM] INFO: Number of atoms of the ANM model: 4697
[ANM] INFO: Number of nodes in the model: (14091, 10)
[lightdock3_setup] ERROR: LightDock setup failed. Please see:
[lightdock3_setup] ERROR: [NormalModesCalculationError] Number of atoms and ANM model differ. Please, check there are no missing nucleotides nor residues.
```

I may be wrong here but I think the dummy atoms acting as the membrane CG beads are also being considered during the normal mode calculations while I was expecting light dock to automatically ignore the membrane beads when `--anm` is used with `--membrane` flag. 

Is there a workaround to do a flexible docking calculation with membranes? Setting the number of receptor modes to zero (`-ar 0 `) seems to work but I would like the receptor to also be flexible. Can you please help me with this? 

I am running lightdock-0.9.0 on Ubuntu within WSL2 

Please let me know if you need additional information to help me. 

Thank you so much for your great contribution! 

Srilok

**Comment by brianjimenez** [comment]
Hi Srilok,

Thank you for reporting this. Indeed, there is no support at the moment to have ANM activated on the receptor when using it together with membrane beads. The workaround you suggested is the only way now to have flexibility on the ligand: `--membrane --anm --ar 0 --al 10`.

Some refactoring work is needed in order to support this on the Python and Rust versions, it would be nice to include this in the next release. For the moment, please use the workaround despite its limitations.

**Comment by Srilok** [comment]
Hi @brianjimenez, 

Thanks for your reply. 

I would also like to add that only fastdfire scoring function seems to work with membranes. For example, if I use the sipper scoring function then I get the following error: 

```
[lightdock] INFO: Using SIPPER scoring function
[lightdock] ERROR: Lightdock has failed, please check traceback:
Traceback (most recent call last):
  File "/home/srilok/anaconda3/envs/lightdock/bin/lightdock3.py", line 26, in <module>
    multiprocessing_simulation(parser)
  File "/home/srilok/anaconda3/envs/lightdock/lib/python3.8/site-packages/lightdock/simulation/docking_multiprocessing.py", line 154, in run_simulation
    scoring_functions, adapters = set_scoring_function(parser, receptor, ligand)
  File "/home/srilok/anaconda3/envs/lightdock/lib/python3.8/site-packages/lightdock/simulation/docking_multiprocessing.py", line 82, in set_scoring_function
    adapter = CurrentModelAdapter(receptor, ligand, receptor_restraints, ligand_restraints)
  File "/home/srilok/anaconda3/envs/lightdock/lib/python3.8/site-packages/lightdock/scoring/functions.py", line 41, in __init__
    self.receptor_model = self._get_docking_model(receptor, receptor_restraints)
  File "/home/srilok/anaconda3/envs/lightdock/lib/python3.8/site-packages/lightdock/scoring/sipper/driver.py", line 48, in _get_docking_model
    indexes = np.array([res_to_index[residue.name] for residue in molecule.residues])
  File "/home/srilok/anaconda3/envs/lightdock/lib/python3.8/site-packages/lightdock/scoring/sipper/driver.py", line 48, in <listcomp>
    indexes = np.array([res_to_index[residue.name] for residue in molecule.residues])
KeyError: 'MMB'
```

It would be great if the membranes handled correctly in the other scoring functions as well.

Thanks again for your contributions 

Regards, 
Srilok

**Comment by brianjimenez** [comment]
Previous and new tests OK, ANM support for receptor in membrane will be added in release `0.9.1`

**Comment by lonngxiang** [comment]
@brianjimenez  similar error；lightdock3_setup.py StructA_remove_HETATM.pdb StructB_remove_HETATM.pdb --noxt --noh --now -anm -rst restraints.list  
![image](https://user-images.githubusercontent.com/40717349/220551404-7c068111-2c8d-48df-8bbf-799c5ad98e64.png)

**Comment by brianjimenez** [comment]
If ANM is enabled, @lonngxiang please make sure there is no missing backbone or sidechain atoms and you use only standard 20 amino acids. You have some warnings before the error popping out (`HIE`, `HDE`...).

Also, please do open your own issue.

**Comment by JorgeRoel** [comment]
Questions (already solved in our publications and tutorials) are not issues. Consider joining the Slack channel instead
