### ISSUE TITLE
can't  multiply sequencce by non-int of type 'Forward'

### ISSUE THREAD

**Issue by tonyageall** [lightdock/lightdock#76]
I can not reproduce your example from the tutorial. My error is:

Traceback (most recent call last):
  File "/home/afarina/SIM_ENV/bin/lightdock3_setup.py", line 93, in <module>
    calculate_anm(receptor, args.anm_rec, args.anm_rec_rmsd, args.anm_seed, DEFAULT_REC_NM_FILE)
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/lightdock/prep/simulation.py", line 136, in calculate_anm
    modes = calculate_nmodes(parsed_lightdock_structure, num_nmodes, rmsd, seed, structure)
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/lightdock/structure/nm.py", line 42, in calculate_nmodes
    num_atoms_prody = prody_molecule.select("protein or nucleic").numAtoms()
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/prody/atomic/atomic.py", line 232, in select
    return SELECT.select(self, selstr, **kwargs)
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/prody/atomic/select.py", line 895, in select
    indices = self.getIndices(atoms, selstr, **kwargs)
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/prody/atomic/select.py", line 953, in getIndices
    torf = self.getBoolArray(atoms, selstr, **kwargs)
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/prody/atomic/select.py", line 1004, in getBoolArray
    parser = self._getParser(selstr)
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/prody/atomic/select.py", line 1103, in _getParser
    parser.enablePackrat()
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/pyparsing/util.py", line 265, in _inner
    return fn(*args, **kwargs)
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/pyparsing/core.py", line 1132, in enable_packrat
    ParserElement.packrat_cache = _FifoCache(cache_size_limit)  # type: ignore[assignment]
  File "/home/afarina/SIM_ENV/lib/python3.10/site-packages/pyparsing/util.py", line 105, in __init__
    keyring = [object()] * size
TypeError: can't multiply sequence by non-int of type 'Forward'

I am not sure where this is coming from. I installed from pip.

**Comment by brianjimenez** [comment]
Please @tonyageall , could you specify which example and version of LightDock did you install (I assume it's the last, but just to double check). If you could also share the exact prompt it would be great.

**Comment by tonyageall** [comment]
release Release 0.9.4 and I was trying to walk through your examples here https://lightdock.org/tutorials/0.9.3/simple_docking fails on lightdock3_setup.py 2UUY_rec.pdb 2UUY_lig.pdb --noxt --noh --now -anm

**Comment by brianjimenez** [comment]
Problem comes from `pyparsing` version 3.1.2, a dependency by ProDy library which is a dependency for LightDock (sorry, no control over it until ProDy nor pyparsing teams fix it). In the meantime, a workaround consists in downgrading the version to 3.1.1. Just type: `pip install pyparsing==3.1.1`

Please, could you confirm this solves the issue?

**Comment by tonyageall** [comment]
works know thank you so much
