### ISSUE TITLE
LightDock not running with any proteins.

### ISSUE THREAD

**Issue by KeaunAmani** [lightdock/lightdock#80]
**Describe the bug**
Any pair of proteins I try to run through lightdock simply fail with the following error (including proteins I've used with LightDock in the past):
Running: lightdock3_setup.py receptor_structure.pdb ligand_structure.pdb --noh --noxt
[lightdock3_setup] INFO: Ignoring OXT atoms
[lightdock3_setup] INFO: Ignoring Hydrogen atoms
[lightdock3_setup] INFO: Reading structure from receptor_structure.pdb PDB file...
[lightdock3_setup] INFO: 1705 atoms, 212 residues read.
[lightdock3_setup] INFO: Ignoring OXT atoms
[lightdock3_setup] INFO: Ignoring Hydrogen atoms
[lightdock3_setup] INFO: Reading structure from ligand_structure.pdb PDB file...
[lightdock3_setup] INFO: 305 atoms, 37 residues read.
[lightdock3_setup] INFO: Calculating reference points for receptor receptor_structure.pdb...
[lightdock3_setup] INFO: Reference points for receptor found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating reference points for ligand ligand_structure.pdb...
[lightdock3_setup] INFO: Reference points for ligand found, skipping
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Saving processed structure to PDB file...
[lightdock3_setup] INFO: Done.
[lightdock3_setup] INFO: Calculating starting positions...
[lightdock3_setup] INFO:   * Surface density: TotalSASA/50.00
[lightdock3_setup] INFO:   * Swarm radius: 10.00 Å
[lightdock3_setup] INFO:   * 180° flip of 50% of starting poses: False
[lightdock3_setup] INFO:   * Ligand Max Diameter: 43.68 Å
[lightdock3_setup] INFO:   * Surface distance: 10.92 Å
Traceback (most recent call last):
  File "/opt/conda/bin/lightdock3_setup.py", line 142, in <module>
    starting_points_files = calculate_starting_positions(
  File "/opt/conda/lib/python3.10/site-packages/lightdock/prep/simulation.py", line 191, in calculate_starting_positions
    starting_points_files = calculate_initial_poses(
  File "/opt/conda/lib/python3.10/site-packages/lightdock/prep/poses.py", line 492, in calculate_initial_poses
    swarm_centers, receptor_diameter, ligand_diameter = calculate_surface_points(
  File "/opt/conda/lib/python3.10/site-packages/lightdock/prep/starting_points.py", line 122, in calculate_surface_points
    molecule = parsePDB(str(pdb_file_name)).select("protein or nucleic or (hetero and not water and not resname MMB)")
  File "/opt/conda/lib/python3.10/site-packages/prody/atomic/atomic.py", line 232, in select
    return SELECT.select(self, selstr, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/prody/atomic/select.py", line 895, in select
    indices = self.getIndices(atoms, selstr, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/prody/atomic/select.py", line 953, in getIndices
    torf = self.getBoolArray(atoms, selstr, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/prody/atomic/select.py", line 1004, in getBoolArray
    parser = self._getParser(selstr)
  File "/opt/conda/lib/python3.10/site-packages/prody/atomic/select.py", line 1103, in _getParser
    parser.enablePackrat()
  File "/opt/conda/lib/python3.10/site-packages/pyparsing/util.py", line 265, in _inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pyparsing/core.py", line 1132, in enable_packrat
    ParserElement.packrat_cache = _FifoCache(cache_size_limit)  # type: ignore[assignment]
  File "/opt/conda/lib/python3.10/site-packages/pyparsing/util.py", line 105, in __init__
    keyring = [object()] * size
TypeError: can't multiply sequence by non-int of type 'Forward'

**To Reproduce**
`Running: lightdock3_setup.py receptor_structure.pdb ligand_structure.pdb --noh --noxt`

**Desktop (please complete the following information):**
 - OS: Debian

**Additional context**
Debian 5.10.209-2 (2024-01-31) x86_64 GNU/Linux

**Comment by alchemistcai** [comment]
https://github.com/lightdock/lightdock/issues/76#issuecomment-2027657704

Here is the same issue and its troubleshooting.

**Comment by KeaunAmani** [comment]
It works thanks
